version: "3.4"
services: 
    api:
        restart: always
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        depends_on: 
            - db
        environment: 
            - PORT=5000
            - CONNECTION_STRING=mongodb://mongo:27017
    client:
        restart: always
        build: 
            context: client
            dockerfile: Dockerfile
            args: 
                - REACT_APP_API=http://localhost:5000
        ports:
            - 3000:80
    db:
        container_name: mongo
        image: mongo:4.2
        restart: always
        ports:
            - 27017:27017
