version: "3.4"
services: 
    api:
        image: node:12.14.1
        restart: always
        working_dir: /home/api
        volumes:
            - ./api:/home/api
        ports:
            - "5000:5000"
        command: "npm start"
        depends_on: 
            - db
        environment: 
            - PORT=5000
            - CONNECTION_STRING=mongodb://mongo:27017
    client:
        restart: always
        build: 
            context: client
            dockerfile: Dockerfile
            args: 
                - REACT_APP_API=http://localhost:5000
        ports:
            - 3000:3000
    db:
        container_name: mongo
        image: mongo:4.2
        restart: always
        ports:
            - 27017:27017
